version: '3.41.0'

set: [pipefail]
shopt: [globstar]

dotenv:
  - '.env'

tasks:
  install-all:
    aliases:
      - all
    deps:
      - install-brew
      - install-warp
      - install-orbstack
    cmds:
      - echo "installed everything.."

  install-brew:
    aliases:
      - brew
    cmds:
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    status:
      - brew --version

  install-warp:
    aliases:
      - warp
    deps:
      - brew
    cmds:
      - brew install --cask warp
    status:
      - brew info warp

  install-starship:
    aliases:
      - starship
    deps:
      - brew
    cmds:
      - brew install starship
    status:
      - brew info starship

  install-raycast:
    aliases:
      - raycast
    deps:
      - brew
    cmds:
      - brew install --cask raycast
    status:
      - brew info raycast

  install-orbstack:
    aliases:
      - orbstack
    deps:
      - brew
    cmds:
      - brew install orbstack
    status:
      - orb version
      - docker --version

  install-vscode:
    aliases:
      - vscode
    deps:
      - brew
    cmds:
      - brew install --cask visual-studio-code
    status:
      - code --version

  install-google-chrome:
    aliases:
      - chrome
    deps:
      - brew
    cmds:
      - brew install --cask google-chrome
    status:
      - brew info google-chrome

  install-chatgpt-app:
    aliases:
      - chatgpt
    deps:
      - brew
    cmds:
      - brew install --cask chatgpt
    status:
      - brew info chatgpt

  install-flameshot:
    aliases:
      - flameshot
    deps:
      - brew
    cmds:
      - brew install --cask flameshot
    status:
      - brew info flameshot

  install-jq:
    aliases:
      - jq
    deps:
      - brew
    cmds:
      - brew install jq
    status:
      - jq --version

  install-yq:
    aliases:
      - yq
    deps:
      - brew
    cmds:
      - brew install yq
    status:
      - yq --version

  install-ripgrep:
    aliases:
      - rg
    deps:
      - brew
    cmds:
      - brew install ripgrep
    status:
      - rg --version

  install-lsd:
    aliases:
      - lsd
    deps:
      - brew
    cmds:
      - brew install lsd
    status:
      - lsd --version

  install-neovim-nightly:
    aliases:
      - nvim
    cmds:
      - mkdir -p /opt/nvim
      - curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz
      - xattr -c ./nvim-macos-arm64.tar.gz
      - tar xzvf nvim-macos-arm64.tar.gz -C /opt/nvim
      - rm -f ./nvim-macos-arm64.tar.gz
      - grep -qxF 'export PATH=/opt/nvim/bin:$PATH' $HOME/.bashrc || echo 'export PATH=/opt/nvim/bin:$PATH' >> $HOME/.bashrc
    status:
      - lsd --version

  install-goenv:
    aliases:
      - goenv
    deps:
      - brew
    cmds:
      - brew install goenv
    status:
      - goenv --version

  install-uv:
    aliases:
      - uv
    cmds:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
    status:
      - uv --version

  install-fd:
    aliases:
      - fd
    deps:
      - brew
    cmds:
      - brew install fd
    status:
      - fzf --version

  install-fzf:
    aliases:
      - fzf
    deps:
      - brew
      - fd
    cmds:
      - brew install fzf
      - grep -qxF 'eval "$(fzf --bash)"' $HOME/.bashrc || echo 'eval "$(fzf --bash)"' >> $HOME/.bashrc
      - grep -qxF 'export FZF_DEFAULT_COMMAND="fd --no-ignore --hidden --exclude \'.git\' --exclude \'.venv\' --exclude node_modules --color=always"' $HOME/.bashrc || echo 'fd --no-ignore --hidden --exclude \'.git\' --exclude \'.venv\' --exclude node_modules --color=always"' >> $HOME/.bashrc
      - grep -qxF 'export FZF_DEFAULT_OPTS="--ansi"' $HOME/.bashrc || echo 'export FZF_DEFAULT_OPTS="--ansi"' >> $HOME/.bashrc
    status:
      - fzf --version

  install-doggo:
    aliases:
      - doggo
    cmds:
      - curl -sS https://raw.githubusercontent.com/mr-karan/doggo/main/install.sh | sh
    status:
      - doggo --version

  install-bat:
    aliases:
      - bat
    deps:
      - brew
    cmds:
      - brew install bat
    status:
      - bat --version

  install-dive:
    aliases:
      - dive
    deps:
      - brew
    cmds:
      - brew install dive
    status:
      - dive --version

  install-yazi:
    aliases:
      - duck
      - yazi
    deps:
      - brew
    cmds:
      - echo "This one takes a few minutes..."
      - brew install yazi ffmpeg sevenzip poppler zoxide imagemagick font-symbols-only-nerd-font
      - grep -qxF 'function y() {' $HOME/.bashrc || cat functions/yazi.sh >> $HOME/.bashrc
      - |
        if [ ! -e $HOME/.config/yazi/yazi.toml ]; then
          cat ./configs/yazi.toml > $HOME/.config/yazi/yazi.toml
        else
          mkdir -p $HOME/.config/yazi
          cat ./configs/yazi.toml > $HOME/.config/yazi/yazi.toml
        fi
    status:
      - yazi --version

  install-sops:
    aliases:
      - sops
    cmds:
      - curl -LO https://github.com/getsops/sops/releases/download/v3.9.4/sops-v3.9.4.darwin.arm64
      - mv sops-v3.9.4.darwin.arm64 $HOME/.local/bin/sops
      - chmod u+x $HOME/.local/bin/sops
    status:
      - sops --version

  install-btop:
    aliases:
      - btop
    deps:
      - brew
    cmds:
      - brew install btop
    status:
      - btop --version

  install-oha:
    aliases:
      - oha
    deps:
      - brew
    cmds:
      - brew install oha
    status:
      - oha --version

  install-posting:
    aliases:
      - posting
    deps:
      - install-uv
    cmds:
      - uv tool install --python 3.12 posting
    status:
      - posting --version

  install-harlequin:
    aliases:
      - harlequin
      - sql-ide
    deps:
      - install-uv
    cmds:
      - uv tool install 'harlequin[postgres,mysql,s3]'
    status:
      - harlequin --version

  install-kubectx:
    aliases:
      - kubectx
    deps:
      - brew
    cmds:
      - brew install kubectx
    status:
      - kubectx -h
      - kubens -h

  install-httpie:
    aliases:
      - httpie
    deps:
      - brew
    cmds:
      - brew install httpie
    status:
      - httpie --version

  install-kubescape:
    aliases:
      - kubescape
    deps:
      - brew
    cmds:
      - brew tap kubescape/tap
      - brew install kubescape-cli
    status:
      - kubescape --version

  install-lazydocker:
    aliases:
      - lazydocker
    deps:
      - brew
    cmds:
      - brew install jesseduffield/lazydocker/lazydocker
    status:
      - lazydocker --version

  install-lazygit:
    aliases:
      - lazygit
    deps:
      - brew
    cmds:
      - brew install jesseduffield/lazygit/lazygit
    status:
      - lazygit --version

  install-age:
    aliases:
      - age
    deps:
      - brew
    cmds:
      - brew install age
    status:
      - age --version

  install-ffmpeg:
    aliases:
      - ffmpeg
    deps:
      - brew
    cmds:
      - brew install ffmpeg
    status:
      - ttyd -version

  install-ttyd:
    aliases:
      - ttyd
    deps:
      - brew
    cmds:
      - brew install ttyd
    status:
      - ttyd --version

  install-vhs:
    aliases:
      - vhs
    deps:
      - brew
      - ttyd
      - ffmpeg
    cmds:
      - brew install vhs
    status:
      - vhs --version

  install-freeze:
    aliases:
      - freeze
    deps:
      - brew
    cmds:
      - brew install charmbracelet/tap/freeze
    status:
      - freeze --version

  install-fastfetch:
    aliases:
      - fastfetch
    deps:
      - brew
    cmds:
      - brew install fastfetch
    status:
      - fastfetch --version
